"""fancy 规则引擎家族：v2 规则引擎、bus 引擎、内置规则数据、技能颜色资源、文本函数库。"""

from __future__ import annotations

from .engine import (
    ApplyResult,
    CompiledAction,
    CompiledCondition,
    CompiledRule,
    CompiledRules,
    RuleValidationError,
    WILDCARD,
    apply_rules,
    compile_rule,
    compile_rulesets,
    get_value,
    parse_structured_path,
    set_value,
    validate_ruleset,
)
from .bus import (
    BUS_FORMAT,
    BUS_VERSION,
    MISSING,
    BusApplyResult,
    BusToken,
    CompiledBus,
    CompiledBusRule,
    CompiledFileMatcher,
    CompiledReplacement,
    IndexToken,
    KeyToken,
    SelectorToken,
    WildcardToken,
    apply_bus,
    compile_bus_ruleset,
    convert_edits_to_bus_ruleset,
    convert_tiaozhua_config,
    is_bus_ruleset,
    is_tiaozhua_config,
    parse_bus_path,
    validate_bus_ruleset,
)
from .builtin_data import (
    EGO_NORMAL_ACTIONS,
    EGO_WARNING_ACTIONS,
    SKILL_COLOR_ACTIONS,
    TEXT_REPLACEMENTS,
    fancy,
)
from .builtin_func import SkillColorHandler, skillColorHandler
from .faust import (
    apply_color_gradient,
    apply_color_gradient_custom,
    extract_text_and_tags,
    hex_to_rgb,
    interpolate_color,
    is_white_color,
    process_dlg_text,
    rgb_to_hex,
)

__all__ = [
    'ApplyResult',
    'CompiledAction',
    'CompiledCondition',
    'CompiledRule',
    'CompiledRules',
    'RuleValidationError',
    'WILDCARD',
    'apply_rules',
    'compile_rule',
    'compile_rulesets',
    'get_value',
    'parse_structured_path',
    'set_value',
    'validate_ruleset',
    'BUS_FORMAT',
    'BUS_VERSION',
    'MISSING',
    'BusApplyResult',
    'BusToken',
    'CompiledBus',
    'CompiledBusRule',
    'CompiledFileMatcher',
    'CompiledReplacement',
    'IndexToken',
    'KeyToken',
    'SelectorToken',
    'WildcardToken',
    'apply_bus',
    'compile_bus_ruleset',
    'convert_edits_to_bus_ruleset',
    'convert_tiaozhua_config',
    'is_bus_ruleset',
    'is_tiaozhua_config',
    'parse_bus_path',
    'validate_bus_ruleset',
    'EGO_NORMAL_ACTIONS',
    'EGO_WARNING_ACTIONS',
    'SKILL_COLOR_ACTIONS',
    'TEXT_REPLACEMENTS',
    'fancy',
    'SkillColorHandler',
    'skillColorHandler',
    'apply_color_gradient',
    'apply_color_gradient_custom',
    'extract_text_and_tags',
    'hex_to_rgb',
    'interpolate_color',
    'is_white_color',
    'process_dlg_text',
    'rgb_to_hex',
]
